### PR TITLE
Generate icon variations with Deno

### LINKED ISSUE #18: Reproducible steps for generating assets
There should be a documented, cross-platform way to generated all the variations of the logo (.ico, .webp, .png, .avif, …).

> [!NOTE]
> For my own website [I use `resvg`, `imagick-wasm` & Deno to generate PNG assets from SVG](https://github.com/mxdvl/mxdvl/blob/0ae1d4a5def21a4dbf1f0a0401ee1442cdf4ab04/deno/scripts/process_icons.ts#L36),
> have [used bash scripts with `vips` & Image Magick’s `convert` previously](https://github.com/mxdvl/mxdvl/blob/main/cmps/generate-favicon.sh),
> and would be happy to raise a PR proposal to this end.

Resolved by #22

### PR DESCRIPTION
**Pull request by mxdvl**
## Why are we doing this?

So that we can have reproducible steps to generate all assets in a reproducible manner, enabling contributors to make modifications to the SVG asset with condifence.

Closes #18 

## What does this change?

- Use [`resvg`](https://github.com/linebender/resvg) & [resvg-js](https://github.com/thx/resvg-js) for rendering the `css.svg`, `css.light.svg` & `css.dark.svg` to PNG buffers (`UInt8Array`) and save them to disk
- Use [`magick-wasm`](https://github.com/dlemstra/magick-wasm) to generate variations for the following formats:
  - JPEG (square, no alpha)
  - JXL
  - AVIF
  - WebP
  - ICO (no multi-size optimisation)
- Manually checked that the colours is indeed `rebeccapurple` / `#639`/ `rgb(102 51 153)` for images. The AVIF & JPEG versions are slightly off with their blue channel at 152.

### CODE REVIEW

**Comment by Que-tin** [comment]
That's annoying.. I mean at least it's better than before, but I wonder what we can do about it.

**Comment by mxdvl** [comment]
AVIF and PNG are lossy image formats that are optimised for small file size over visual perfection, and take for granted that blue sensitivity is lesser in most humans, so it’s probably an acceptable compromise?

**Review by argyleink — COMMENTED** [review]
color seems more lossless with this, runs locally great

the jpeg version vs the jpg version need a tweak, both in we gotta figure out which we want to use and then we need to provide a non-rounded corner variant for the variants without transparency (so black doesnt show up at the edges)

but this is great, definitely a great addition for reproduceability and color fidelity, ty!

**Comment by argyleink** [comment]
todo 🚀 
- [ ] light/dark variants
- [ ] square variants
- [ ] 2x variants

**Comment by Que-tin** [comment]
@mxdvl @argyleink I managed to maintain the correct color with sharp. I'll open a PR once I'm done.

**Comment by mxdvl** [comment]
I’m not entirely sure what the benefit of the @2x variants is, as the files are all pretty small…

**Comment by argyleink** [comment]
you've done great work here to spur the conversation and pave the path! looks like we're going to go with Sharp instead over at #22, so this can close. i feel like you should make a small edit to #21 so you can "co authored" the work, making sure you get cred for your influence and contributions.

**Comment by Que-tin** [comment]
> you've done great work here to spur the conversation and pave the path! looks like we're going to go with Sharp instead over at #22, so this can close. i feel like you should make a small edit to #22 so you can "co authored" the work, making sure you get cred for your influence and contributions.

Agree!

**Comment by mxdvl** [comment]
Brill – I’ve got more things coming for this repo 😉 so I won’t be too sad [if it’s complicated to get co-authorship this time](https://github.com/CSS-Next/logo.css/pull/22#issuecomment-2474725375).

**Pull request closed without merging**
