### PR TITLE
fix: More efficient shapes and paths

### PR DESCRIPTION
**Pull request by rol4nd909**
Optimised and update the SVG's as suggested in #27 since we use this as our base logo I also aligned the characters `C` and `S`

### CODE REVIEW

**Comment by itsjavi** [comment]
@rol4nd909 I like the alignment of the "C" but how are we going to represent this in HTML/CSS? we might need a fork of DINish and create our own font at the end, also to solve #14

**Comment by rol4nd909** [comment]
> @rol4nd909 I like the alignment of the "C" but how are we going to represent this in HTML/CSS? we might need a fork of DINish and create our own font at the end, also to solve #14

Yeah I was trying to change the font my self, but I think I used a different DINish you can see my try here:

https://codepen.io/ROL4ND909/pen/BaXvgPW?editors=0110

**Comment by mxdvl** [comment]
If you're willing to wait a day or two I've got a version of what I proposed in the original issue that does away with fonts entirely and may hopefully be satisfactory…

**Comment by rol4nd909** [comment]
@mxdvl what doe you mean with 'away with fonts entirely'? And might be an idea to add your work in this branch?

**Comment by argyleink** [comment]
discussed in the call today, helped provide the more precise font used. @rol4nd909 has what he needs now, to be discussed more once a new commit with heavier font is used 👍🏻

**Comment by rol4nd909** [comment]
I've updated the codepen with a new edited version of the DINish Preview font, the version we used was the `DINish Preview Condensed Heavy` and `letter-spacing: -.05ch;`,  or when used as variable font  `font-variation-settings: "wdth" 75, "wght" 800;`

https://codepen.io/ROL4ND909/pen/BaXvgPW?editors=0110

**Comment by itsjavi** [comment]
if we have a font (or soon) it means that we can move forward with this PR I would say :) 

The only change I would do is to not revert #29 and go back using arcs like @myfonj suggested. After that I think we can move forward and merge

**Comment by rol4nd909** [comment]
@itsjavi I change the path back to using arcs now.

**Comment by itsjavi** [comment]
After downloading and analyzing it more closely it seems that the changes done in #33
have been reverted as well.

Did you use the latest SVG that is on master or (probably) the previous version?

You can see that also by comparing them here with the sliders: https://github.com/CSS-Next/logo.css/pull/35/files 

https://github.com/user-attachments/assets/5bafa236-7521-4223-b730-77ace69f13e3

Sorry for this back and forth

**Comment by rol4nd909** [comment]
I will check tomorrow, I had changed the end caps in the font both top and bottom where misaligned between the c and s

**Comment by rol4nd909** [comment]
I updated the colors to use named colors loved the idea of  https://github.com/CSS-Next/logo.css/pull/45#discussion_r1849914618 made by @mxdvl 💜

**Comment by rol4nd909** [comment]
@itsjavi Ah no thats sad... It does support the short version `#639` or does it need to be the full `#663399`

**Comment by itsjavi** [comment]
@rol4nd909 short hex is fine, afaik.

**Comment by rol4nd909** [comment]
@argyleink @Que-tin please let me know if we can merge or still need to wait.

**Review by argyleink — APPROVED** [review]
it's ok if we dont have a font file ready for HTML variants, I dont think that should block this merging. inline svg totally works and offers plenty of customization (maybe even offering higher fidelity with less ways to deviate).

nice work here!

**Review by itsjavi — APPROVED** [review]

**Pull request merged**
