### PR TITLE
Hand-crafted logo letters

### LINKED ISSUE #14: what to do with the end caps not aligning
some people think it's glaringly bad, some dont notice, some will never see it at the tiny size they'll usually see it, other's might print it on a poster and be appalled. a couple questions:

- if we solve it, then we cant just point to the Dinish font
- if we solve it, how will we distribute the glyphs/shapes

### LINKED ISSUE #27: More efficient shapes and paths
This may be unnecessary optimiziation, but is there a reason why the file has such complex and long paths? Especially the container, which is a simple rectangle with 3 rounded corners:

`<path fill="#639" d="M0 0H840C882.435 0 923.131 16.8571 953.137 46.8629C983.143 76.8687 1000 117.565 1000 160V840C1000 882.435 983.143 923.131 953.137 953.137C923.131 983.143 882.435 1000 840 1000H160C117.565 1000 76.8687 983.143 46.8629 953.137C16.8571 923.131 0 882.435 0 840V0Z"/>`

Those 284 bytes could be reduced to 169 using a simpler path (which in my opinion would be easier to read and understand too):

`<path fill="#639" d="M0,0 C0,0 0,0 840,0 928,0 1000,72 1000,160 1000,160 1000,840 1000,840 1000,928 928,1000 840,1000 840,1000 160,1000 160,1000 72,1000 0,928 0,840Z"/>`

And if we are not attached to a single path method, we could even simplify it more (to 102 bytes) using two rectangles, one with a radius, and the other one without:

`<rect fill="#639" width="1000" height="1000" rx="160"/><rect fill="#f008" width="300" height="300"/>`

And using groups, reduced it to 95 characters:

`<g fill="#639"><rect width="1000" height="1000" rx="160"/><rect width="300" height="300"/></g>`

From 284 to 95 is a 66% size reduction, only on that path. I haven't tested the letters, but they would offer some optimization too (although I doubt a 66%).

----

As I was writing the issue, I passed the SVG file through the [SVG OMG](https://jakearchibald.github.io/svgomg/) tool, and the file size goes down from 2.78KB to 1.88KB

```
<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="1000">
  <path fill="#639" d="M0 0h840a160 160 0 0 1 160 160v680a159.999 159.999 0 0 1-160 160H160A159.999 159.999 0 0 1 0 840V0Z"/>
  <path fill="#fff" d="M817.5 923.1c-32.3 0-57-9.4-74.3-28.3-17.1-19-26-46.1-26.8-81.5H786c.4 31.3 11.4 47 33 47 11 0 18.8-3.5 23.3-10.4 4.4-6.9 6.7-17.9 6.7-33 0-12-3-22-8.8-29.9a73 73 0 0 0-29.4-21.1L785 753.5c-23-11-39.7-24-50-39.2-10-15.1-15-36.3-15-63.4 0-30.3 8.8-54.9 26.3-73.8 18-18.9 42.5-28.3 73.8-28.3 30.2 0 53.6 9.3 70.1 27.8 16.8 18.6 25.6 45.2 26.3 80h-67a72.011 72.011 0 0 0-6.7-33c-3.8-7.6-11.2-11.4-22.2-11.4-19.6 0-29.4 11.7-29.4 35 0 11.8 2.4 21 7.2 28a65.002 65.002 0 0 0 25.3 17.4l24.7 10.9c25.5 11.7 43.9 26 55.2 43.3 11.4 17.2 17 40.2 17 69 0 34.5-9 61-27.3 79.5-18.2 18.5-43.5 27.8-75.8 27.8Zm-224.8 0c-32.3 0-57-9.4-74.3-28.3-17.1-19-26-46.1-26.8-81.5h69.6c.4 31.3 11.4 47 33 47 11 0 18.8-3.5 23.2-10.4 4.5-6.9 6.7-17.9 6.7-33 0-12-2.9-22-8.7-29.9a73 73 0 0 0-29.4-21.1l-25.8-12.4c-23-11-39.7-24-50-39.2-10-15.1-15-36.3-15-63.4 0-30.3 8.8-54.9 26.3-73.8 18-18.9 42.5-28.3 73.8-28.3 30.2 0 53.6 9.3 70 27.8 17 18.6 25.7 45.2 26.4 80h-67a72.011 72.011 0 0 0-6.7-33c-3.8-7.6-11.2-11.4-22.2-11.4-19.6 0-29.4 11.7-29.4 35 0 11.8 2.4 21 7.2 28a65.002 65.002 0 0 0 25.3 17.4l24.7 10.9c25.5 11.7 43.9 26 55.2 43.3 11.3 17.2 17 40.2 17 69 0 34.5-9.1 61-27.3 79.5-18.2 18.5-43.5 27.8-75.8 27.8Zm-234.1 0c-31.6 0-56.7-8.6-75.3-25.8-18.6-17.1-27.8-42.8-27.8-76.8v-168c0-33.8 9.8-59.4 29.4-77 19.9-17.4 46-26.2 78.3-26.2 31.3 0 56 9 74.3 26.8 18.5 17.9 27.8 44.5 27.8 80v13.3h-73.7v-12.9c0-13.7-3-23.8-8.8-30.4a26.397 26.397 0 0 0-21.6-10.3c-12 0-20.5 4.1-25.3 12.4a78.99 78.99 0 0 0-6.7 36.6v146c0 30.5 10.7 46 32 46.3 10 0 17.5-3.6 22.7-10.8a51.7 51.7 0 0 0 7.7-30.4V805h73.7v11.4c0 23.7-4.6 43.5-13.9 59.3a88.597 88.597 0 0 1-38.1 35.6 121.002 121.002 0 0 1-54.7 11.8Z"/>
</svg>
```

### LINKED ISSUE #31: changing fill programatically when generating assets
I propose to have a single SVG master file (easier to maintain) and change the fills (light, dark, primary) programatically when generating the assets.

We could use some XML / SVG library for that, or just replace string literals. For the square version we only need to change the first path with a rect.

### PR DESCRIPTION
**Pull request by mxdvl**
## Why are we doing this?

By carefully creating the paths for the CSS letters in the logo, we:
- get aligned caps, like @chriskirknielsen’s version
- remove the need for contributor to acquire expensive design software
- stop relying on external fonts
- ensure the SVG has an accessible title
- achieve minimal file size out-of-the box
- can create stylistic variants programatically
- use the platform!

This comes at the cost of better understanding of the SVG internals, which is mitigated by:
- the [excellent MDN documentation for `d`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d)
- detailed visual explanation of the functions used
- [an interactive version to play with parameter values](https://codepen.io/mxdvl/pen/zYgbKBe)

## What does this change?

- [X] Adds a script used to draw the CSS logo as an SVG
- [X] Document what each parameter for drawing each shape
- [x] Adjust the parameters so the logo is visually satisfactory
- [x] Handle both variants
- [X] [Link to a playground for contributors to adjust](https://codepen.io/mxdvl/pen/zYgbKBe)

--- 

Closes #35 
Closes #27 
Closes #14
Closes #31

### CODE REVIEW

**Comment by rol4nd909** [comment]
It's awesome how this works but as been said in #13

"I think it would be unfortunate if we need JavaScript to render a logo for CSS"

**Comment by mxdvl** [comment]
> "I think it would be unfortunate if we need JavaScript to render a logo for CSS"

The logo will be entirely static – the JS is only doing the work that is currently done by Figma.

**Comment by rol4nd909** [comment]
Ah fair point never mind then ;)

**Comment by rol4nd909** [comment]
Is there I reason that you changed the size of 1000x1000 to 240x240? And I really think you should try to add the `<title id="title">` and `<desc id="description">` and the `role="img"` `aria-labelledby="title description"` and fields should be editable.

**Comment by romainmenke** [comment]
I kinda get this change but I also wonder if it will make it harder to approach the logo from a designer perspective.

Having Figma as a source of truth is a good thing I think.

**Comment by itsjavi** [comment]
I appreciate all this work but I think it will make it harder to maintain and to make design changes. I agree with @romainmenke here.

I still think we should have a master `css.svg` file as the source of truth, and just use JS to create the other ones (square, black, white) changing fills like I said in #31

**Comment by mxdvl** [comment]
Absolutely understand if this is not a desirable change. Having felt firsthand as a designer the stronghold of proprietary software being used to generate assets I try to offer alternatives especially if they can be of public benefit. Feel free to close this PR if it is not a step in the right direction for the CSS logo.

I doubt you'll find a way to consistently create accessible SVG files from Figma, Illustrator or even Inkscape, but I would also love to be proved wrong so if you find an elegant solution to this conenendrum please share it here so I can get notified 🙇

**Comment by romainmenke** [comment]
> I doubt you'll find a way to consistently create accessible SVG files from Figma, Illustrator or even Inkscape, but I would also love to be proved wrong so if you find an elegant solution to this conenendrum please share it here so I can get notified

Maybe this is something that can be done with post processing with something like `post-html`?

**Comment by itsjavi** [comment]
Figma export was done only once, and further changes can be done in any software supporting SVG. After the changes and exporting the file we can use tools like SVGOMG and then add the missing A11Y data to the XML.

I don't think we will need to change it often after we solve the font problems.

Also, having a single SVG file as source of truth (and the rest generated from it) it helps with the maintenance.

After all your effort, I'd rather wait to see what other contributors think before closing this PR or not

Voting the original post can help

**Comment by mxdvl** [comment]
### @rol4nd909 

> Is there I reason that you changed the size of 1000x1000 to 240x240?

I initially thought 240 was a more easily divisible number, but for the sake of consistency I’ve kept it as 1000 &times; 1000 in [`7487d07`](https://github.com/CSS-Next/logo.css/pull/39/commits/7487d07c0b239a8b4340bab08ef5824f6ea91388)

> I really think you should try to add the `<title id="title">` and `<desc id="description">` and the `role="img"` `aria-labelledby="title description"` and fields should be editable.

Agreed, added in [`efc7c30`](https://github.com/CSS-Next/logo.css/pull/39/commits/efc7c30739b5daee3859ae944bc40d4a02078850) & [`9f38efc3`](https://github.com/CSS-Next/logo.css/pull/39/commits/9f38efc33239e6e6fba692b069516ef1ca2d0a77)

---

### @itsjavi 

> I appreciate all this work but I think it will make it harder to maintain and to make design changes

Is this assessment [based on having tried the interactive version](https://codepen.io/mxdvl/pen/zYgbKBe)? Would it help if that version had [interactive bezier handles](https://yqnn.github.io/svg-path-editor/#P=M_65_-75_C_65_-105_60_-155_0_-155_C_-60_-155_-65_-105_-65_-75_L_-65_75_C_-65_105_-60_155_0_155_C_60_155_65_105_65_75) to enable manually modifying the control points?

> I don't think we will need to change it often after we solve the font problems.

Agreed – this proposal being one approach that leads to solving the font problem, while also addressing some design issues raised in #14.

> **After all your effort**, I'd rather wait to see what other contributors think before closing this PR or not

I’ve enjoyed doing this and do not consider it to be a waste of my time even if it ends up being rejected.

**Comment by argyleink** [comment]
Lovely thread y'all, so nice to see healthy contributors and community working together towards a healthy repo ❤️ 

I agree with Javi and Roland here

> Figma export was done only once, and further changes can be done in any software supporting SVG. After the changes and exporting the file we can use tools like SVGOMG and then add the missing A11Y data to the XML.
> 
> I don't think we will need to change it often after we solve the font problems.

The SVG file, one that people can read and reason with, while it's not the DRYest solution out there, it does strike the healthy balance if approachability and maintainability.

This work @mxdvl is very coo, and I bet (i'd also read and share it) you could write a super fun blog post on what you did and share it for anyone else that wants to learn from it or use the output you create from it. That way the great work can continue to live on.

I'm going to close this for now, as the community group discussed this today and decided to continue maintaining the sources as SVG. Thanks again for the kind contributor dialog and sharing this super cool work with us.

**Comment by mxdvl** [comment]
Thank you for the feedback, I’ll definitely write about it, as this is [not the first time](https://github.com/sveltejs/branding/pull/10) I’ve [proposed hand-crafted logo](https://github.com/jsr-io/jsr/pull/268).

> decided to continue maintaining the sources as SVG

Would this mean that you’d consider a PR that uses the output of this function directly to the SVG files, similar to https://github.com/mxdvl/logo.css/pull/1?

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" width="240" fill="none" role="img" aria-labelledby="css-title css-description">
  <title id="css-dark-title">CSS Logo</title>
  <desc id="css-dark-description">A purple square with rounded corners and the letters CSS inside in white</desc>
  <path d="M0,0H840 A 160 160 0 0 1 1000 160V840A 160 160 0 0 1 840 1000H160A 160 160 0 0 1 0 840Z" fill="rebeccapurple"></path>
  <g class="CSS" stroke-width="72" stroke="white" transform="translate(820 730)">
    <path class="C" transform="translate(-464 0)" d="M 65,-75C 65,-105 60,-155 0,-155C -60,-155 -65,-105 -65,-75L -65,75C -65,105 -60,155 0,155C 60,155 65,105 65,75"></path>
    <path class="S" transform="translate(-232 0)" d="M 65,-75C 65,-105 60,-155 0,-155C -60,-155 -65,-105 -65,-75C -65,25 65,-25 65,75C 65,105 60,155 0,155C -60,155 -65,105 -65,75"></path>
    <path class="S" transform="translate(-0 0)" d="M 65,-75C 65,-105 60,-155 0,-155C -60,-155 -65,-105 -65,-75C -65,25 65,-25 65,75C 65,105 60,155 0,155C -60,155 -65,105 -65,75"></path>
  </g>
</svg>
```

I’m only asking as your comments make no mention of visual fidelity and wanted to make sure that it was understood that I would still consider the SVG as the source of truth :)

**Comment by mxdvl** [comment]
> Tbh, I prefer the current one because it uses curves instead of strokes for the text (some tools to create fonts out of SVGs require converting/expanding strokes to curves),

Fair!

> and arcs instead of bezier curves (#29) which are more precise.

This one does too, see the [`A` being used in the first `path`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/d#elliptical_arc_curve), here expanded out:

```txt
 M 0,0
 H 840
 A 160 160 0 0 1 1000 160
 V 840
 A 160 160 0 0 1 840 1000
 H 160
 A 160 160 0 0 1 0 840Z
```

> SVG transforms also seem to have [partial browser support](https://caniuse.com/?search=svg%20transform) currently.

[Not really, `transform` is supported by every browser since Dec 2010](https://caniuse.com/mdn-api_svggraphicselement_transform). The [`transform` attribute of SVG element](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/transform) is not the same thing as the [`transform` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/transform).

> What I like is that the paths for the text are more compact. Is there a way to do the same with expanded stroke, as only curves?

I doubt it, as you’ll need to trace the “inner” and “outer” lines of the SVG, so you’ll end up with something close to the current version even if you nudge the paths ever so slightly. The whole point of this proposal is to use `stroke`s instead of `fill`s 😁 

> Also, it might be some missing fill and the view box, but this is what I see when opening it on Affinity Designer 2:

I’ve [updated my post above to include an explicit `height` & `width` attribute](https://github.com/CSS-Next/logo.css/pull/39#issuecomment-2485825366), which should help!

**Comment by itsjavi** [comment]
thank you @mxdvl ! I am learning a lot about SVG syntax thanks to you.

I wouldn't mind using strokes much (at the end you can just expand them in vector tools), but the only problem I see is that the design varies from the original font, making it complex for designers to use "the CSS font" for other purposes (e.g. banners, etc). Looks very similar though.

https://github.com/user-attachments/assets/50b958e5-dd83-468f-840e-c4c534b367ea

**Pull request closed without merging**
