### PR TITLE
Adding JXL lossless versions for all images

### PR DESCRIPTION
**Pull request by radum**
Converted all png files using the latest version of JPG XL like this: 

```bash
fd -e png --exec cjxl {} {.}.jxl --compress_boxes 0
```

That will give you lossless conversion and preserves the metadata.

### CODE REVIEW

**Comment by mxdvl** [comment]
The current assets are generated using a script for maximum reproducibility, so [I’d suggest extending the sharp implementation](https://github.com/CSS-Next/logo.css/pull/22#discussion_r1841112708) rather than running this as a manual step.

**Comment by Que-tin** [comment]
Different approach, do we really need to provide a JPG XL?
Just want to understand the usecase that makes it necessary to include a JPG XL.

**Comment by Que-tin** [comment]
@radum Any specific use cases?

**Comment by radum** [comment]
@mxdvl I didn't realise there is sharp involved also. I will close this and reopen if we want jxl in here via sharp.

@Que-tin I use JXL all the time as OSX supports it now. I don't want to go into a what format is the best debacle here as its not the point. I just think that even is support inside browsers is skim now JXL has a really wide support within the editing ecosystem, its pretty much supported everywhere.

And those assets are going to be used with that also. 

To be honest I don't mind at the end of the day as I can convert them, I just thought would be great if we have jxl in there as an option as we have the other ones.

**Pull request closed without merging**
